name: Executar Script de Previsao

on:
  schedule:
    # O horário é em UTC (3 horas a mais que Brasília). 
    # '0 11 * * *' roda às 08:00 da manhã no Brasil.
    - cron: '0 11 * * *'
  workflow_dispatch: # Isso permite que você rode o script manualmente com um botão

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v3

      - name: Configurar o Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar o script principal
        run: python main.py  # Coloque o nome do arquivo que inicia tudo
